name: Build and Push Gitpod Image to GHCR

on:
  workflow_dispatch:
    inputs:
      class:
        description: 'Benchmark class'
        required: true
        default: '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHCR_TOKEN }}
 
    - name: Extract image name
      id: image_name
      run: echo "IMAGE_NAME=ghcr.io/wankunde/velox_prebuild:20240527" >> $GITHUB_ENV
 
    - name: Build Docker Image
      uses: docker/build-action@v2
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
 
    - name: Push Docker Image to GHCR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./scripts/gitpod.dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}
